export type FeatureType = 'command' | 'command_pattern' | 'registry' | 'json_field' | 'function_macro'

export interface FeatureRule {
  id: string
  description: string
  type: FeatureType
  match: string
  minVersion: string
  maxVersion?: string
  fix?: string
  note?: string
}

export const FEATURE_RULES: FeatureRule[] = [
  {
    id: 'random',
    description: 'The /random command (value, roll, reset) was added.',
    type: 'command',
    match: 'random',
    minVersion: '1.20.2',
    fix: 'Replace with /scoreboard random (1.20.4) or a custom RNG via /scoreboard.',
    note: 'Added in 23w31a',
  },
  {
    id: 'damage',
    description: 'The /damage command was added.',
    type: 'command',
    match: 'damage',
    minVersion: '1.19.4',
    fix: 'Use /effect with instant damage, /attribute, or /data to manage health in older versions.',
    note: 'Added in 23w06a (1.19.4)',
  },
  {
    id: 'ride',
    description: 'The /ride command was added.',
    type: 'command',
    match: 'ride',
    minVersion: '1.19.4',
    fix: 'Use /tp or /data merge for entity mounting in older versions.',
    note: 'Added in 23w03a (1.19.4)',
  },
  {
    id: 'return',
    description: 'The /return command for functions was added.',
    type: 'command',
    match: 'return',
    minVersion: '1.20',
    fix: 'Restructure function logic to not early-return.',
    note: 'Added in 23w16a (1.20)',
  },
  {
    id: 'fillbiome',
    description: 'The /fillbiome command was added.',
    type: 'command',
    match: 'fillbiome',
    minVersion: '1.19.3',
    fix: 'Use /fill with biome NBT or world editing tools in older versions.',
    note: 'Added in 22w46a (1.19.3)',
  },
  {
    id: 'place',
    description: 'The /place command (feature/structure/jigsaw/template) replaced /placefeature.',
    type: 'command',
    match: 'place',
    minVersion: '1.19',
    fix: 'Pre-1.19 uses /placefeature (1.18) or /locate + manual building.',
    note: 'Added in 22w11a (1.19)',
  },
  {
    id: 'tick',
    description: 'The /tick command (sprint/step/freeze/rate) was added.',
    type: 'command',
    match: 'tick',
    minVersion: '1.20.3',
    fix: 'Note: /tick is an admin/debug command and is NOT available in command blocks/datapacks by default.',
    note: 'Added in 23w43a (1.20.3); requires elevated permissions',
  },
  {
    id: 'transfer',
    description: 'The /transfer command was added.',
    type: 'command',
    match: 'transfer',
    minVersion: '1.20.5',
    fix: 'Transfer is 1.20.5+ only; no direct replacement in older versions.',
    note: 'Added in 24w04a (1.20.5)',
  },
  {
    id: 'function_macro',
    description: 'Function macros with $(variable) and line continuation require 1.20.4+',
    type: 'function_macro',
    match: '\\$\\(',
    minVersion: '1.20.4',
    fix: 'Macros are 1.20.4+. Use /function with multiple hardcoded functions for older versions.',
    note: 'Macros + line continuation added in 23w45a',
  },
  {
    id: 'item_components_give',
    description: 'Item components [components] syntax in /give requires 1.20.5+',
    type: 'command_pattern',
    match: '^/?(?:give|clear)\\s+\\S+\\s+[\\w.:-]+\\[',
    minVersion: '1.20.5',
    fix: 'Use NBT tag:{...} instead of [components] for pre-1.20.5, or split by version.',
    note: 'Item component format changed in 24w09a',
  },
  {
    id: 'item_command',
    description: 'The /item command (replace/modify) overhaul requires 1.20.5+',
    type: 'command',
    match: 'item',
    minVersion: '1.20.5',
    fix: 'Use /replaceitem (pre-1.20.5) — note /item is the new preferred form in 1.20.5+.',
    note: 'Item component rework in 24w09a',
  },
  {
    id: 'execute_if_items',
    description: '/execute (if|unless) items requires 1.20.5+',
    type: 'command_pattern',
    match: '^/?(?:execute\\b.*\\b)(?:if|unless)\\s+items\\b',
    minVersion: '1.20.5',
    fix: 'Use /execute if data with NBT checks for item detection in older versions.',
    note: 'Added with component rework',
  },
  {
    id: 'attribute',
    description: 'The /attribute command was added in 1.16.',
    type: 'command',
    match: 'attribute',
    minVersion: '1.16',
    fix: 'Use /data merge for attribute modifiers in pre-1.16 versions.',
    note: 'Added in 20w17a (1.16)',
  },
  {
    id: 'bossbar_players',
    description: '/bossbar set players subcommand requires 1.20.5+',
    type: 'command_pattern',
    match: '^/?(?:bossbar\\b.*\\b)players\\b',
    minVersion: '1.20.5',
    fix: 'Add players via /bossbar add then /bossbar set players in 1.20.5+.',
    note: 'bossbar players added 24w09a',
  },
  {
    id: 'schedule',
    description: 'The /schedule command was added in 1.14.',
    type: 'command',
    match: 'schedule',
    minVersion: '1.14',
    fix: 'Use a ticking function with /scoreboard timers in pre-1.14.',
    note: 'Added in 18w43a (1.14)',
  },
  {
    id: 'execute_if_unless',
    description: '/execute (if|unless) subconditions require 1.14+',
    type: 'command_pattern',
    match: '^/?(?:execute\\b.*\\b)(?:if|unless)\\s+',
    minVersion: '1.14',
    fix: 'Pre-1.14 /execute cannot conditionally test; use /testfor + /stats.',
    note: 'execute if/unless added in 1.14',
  },
  {
    id: 'namespaced_ids',
    description: 'Namespaced IDs (minecraft:stone) and new /give syntax require 1.13+',
    type: 'command_pattern',
    match: '^/?(?:give|clear|replaceitem)\\s+\\S+\\s+minecraft:',
    minVersion: '1.13',
    fix: 'Pre-1.13 uses numeric item IDs. Use a legacy datapack for old versions.',
    note: '1.13 Aquatic command overhaul',
  },
  {
    id: 'wolf_variant',
    description: 'minecraft:wolf_variant registry added in 1.21.5',
    type: 'registry',
    match: 'wolf_variant',
    minVersion: '1.21.5',
    fix: 'Remove wolf_variant references for pre-1.21.5.',
    note: 'Added in 1.21.5',
  },
  {
    id: 'pig_variant',
    description: 'minecraft:pig_variant registry added in 1.21.5',
    type: 'registry',
    match: 'pig_variant',
    minVersion: '1.21.5',
    fix: 'Remove pig_variant references for pre-1.21.5.',
    note: 'Added in 1.21.5',
  },
  {
    id: 'enchantment_registry',
    description: 'minecraft:enchantment registry (custom enchantments) requires 1.21+',
    type: 'registry',
    match: 'enchantment',
    minVersion: '1.21',
    fix: 'Custom enchantments are 1.21+ only.',
    note: 'Added in 1.21 (Tricky Trials)',
  },
  {
    id: 'enchantment_ref',
    description: 'Referencing a custom enchantment registry entry (enchantment/foo) requires 1.21+',
    type: 'registry',
    match: 'enchantment/',
    minVersion: '1.21',
    fix: 'Custom enchantments are 1.21+ only.',
    note: 'Added in 1.21 (Tricky Trials)',
  },
  {
    id: 'jukebox_song',
    description: 'minecraft:jukebox_song registry requires 1.21+',
    type: 'registry',
    match: 'jukebox_song',
    minVersion: '1.21',
    fix: 'Custom jukebox songs are 1.21+ only.',
    note: 'Added in 1.21',
  },
  {
    id: 'test_command',
    description: 'The /test command (game test framework) requires 1.21.4+',
    type: 'command',
    match: 'test',
    minVersion: '1.21.4',
    fix: 'Game test commands are 1.21.4+ only.',
    note: 'Added in 1.21.4',
  },
  {
    id: 'return_run',
    description: '/return run requires 1.20.4+',
    type: 'command_pattern',
    match: '^/?(?:return\\s+run)',
    minVersion: '1.20.4',
    fix: 'Use /return (no run) or restructure for pre-1.20.4.',
    note: 'Added in 1.20.4',
  },
  {
    id: 'rotate',
    description: 'The /rotate command (rotate entities) was added.',
    type: 'command',
    match: 'rotate',
    minVersion: '1.21.2',
    fix: 'Rotate is 1.21.2+ only; use /data merge to set Rotation NBT in older versions.',
    note: 'Added in 24w40a (1.21.2)',
  },
  {
    id: 'version_cmd',
    description: 'The /version command was added.',
    type: 'command',
    match: 'version',
    minVersion: '1.21.6',
    fix: 'Version is 1.21.6+ only.',
    note: 'Added in 25w15a (1.21.6)',
  },
  {
    id: 'waypoint',
    description: 'The /waypoint command (Locator Bar) was added.',
    type: 'command',
    match: 'waypoint',
    minVersion: '1.21.6',
    fix: 'Waypoints are 1.21.6+ only (Locator Bar feature).',
    note: 'Added in 25w15a/25w17a (1.21.6)',
  },
  {
    id: 'dialog',
    description: 'The /dialog command (NPC dialog) was added.',
    type: 'command',
    match: 'dialog',
    minVersion: '1.21.6',
    fix: 'Dialog is 1.21.6+ only.',
    note: 'Added in 25w20a (1.21.6)',
  },
  {
    id: 'fetchprofile',
    description: 'The /fetchprofile command was added.',
    type: 'command',
    match: 'fetchprofile',
    minVersion: '1.21.9',
    fix: 'Fetchprofile is 1.21.9+ only.',
    note: 'Added in 25w34a (1.21.9)',
  },
  {
    id: 'swing',
    description: 'The /swing command (animate arm swing) was added.',
    type: 'command',
    match: 'swing',
    minVersion: '26.1',
    fix: 'Swing is 26.1+ only.',
    note: 'Added in 26.1 snapshot 1',
  },
  {
    id: 'unpublish',
    description: 'The /unpublish command (LanServerProperties) was added.',
    type: 'command',
    match: 'unpublish',
    minVersion: '26.2',
    fix: 'Unpublish is 26.2+ only.',
    note: 'Added in 26.2 snapshot 8',
  },
  {
    id: 'posteffect',
    description: 'The /posteffect command was added.',
    type: 'command',
    match: 'posteffect',
    minVersion: '26.3',
    fix: 'Posteffect is 26.3+ only.',
    note: 'Added in 26.3 snapshot 3',
  },
  {
    id: 'item_model_component',
    description: 'minecraft:item_model component requires 1.21.4+',
    type: 'command_pattern',
    match: '^/?(?:give|item|clear|loot)\\b[^\\n]*minecraft:item_model\\b',
    minVersion: '1.21.4',
    fix: 'item_model component is 1.21.4+; use numeric CustomModelData or resource-pack overrides for older versions.',
    note: 'item_model added 1.21.4 (DataComponents)',
  },
  {
    id: 'custom_model_data_compound',
    description: 'custom_model_data with floats/flags/strings/colors fields requires 1.21.4+',
    type: 'command_pattern',
    match: '^/?(?:give|item|clear|loot)\\b[^\\n]*custom_model_data=\\{[^}]*(?:floats|flags|strings|colors)\\b',
    minVersion: '1.21.4',
    fix: 'The rich custom_model_data format (floats/flags/strings/colors) is 1.21.4+; use a single integer value (custom_model_data=<n>) for 1.20.5-1.21.3.',
    note: 'custom_model_data extended format added 1.21.4',
  },
  {
    id: 'consumable_component',
    description: 'minecraft:consumable component requires 1.21.2+',
    type: 'command_pattern',
    match: '^/?(?:give|item|clear|loot)\\b[^\\n]*minecraft:consumable\\b',
    minVersion: '1.21.2',
    fix: 'consumable component is 1.21.2+; the food component alone no longer triggers consumption in 1.21.2+ (add consumable={}).',
    note: 'consumable component added 1.21.2; food no longer auto-consumes',
  },
]
