export interface ResourceFeatureRule {
  id: string
  description: string
  match: string
  minVersion: string
  maxVersion?: string
  fix?: string
  note?: string
}

export const RESOURCE_FEATURE_RULES: ResourceFeatureRule[] = [
  {
    id: 'item_model_type',
    description: 'Item models use the "model" type field (added 1.21.5)',
    match: 'model.*type',
    minVersion: '1.21.5',
    fix: 'Omit the type field for pre-1.21.5 item models.',
    note: 'Item model type field added in 1.21.5',
  },
  {
    id: 'gui_font_variants',
    description: 'Font provider "space" variant with advancements field',
    match: 'font/',
    minVersion: '1.20.5',
    fix: 'Remove advancements field from space font providers for pre-1.20.5.',
    note: 'Font advancements field added 1.20.5',
  },
  {
    id: 'equipment_model_asset_id',
    description: 'Equipment model field renamed from "model" to "asset_id" (1.21.5)',
    match: 'asset_id',
    minVersion: '1.21.5',
    fix: 'Use "model" instead of "asset_id" for pre-1.21.5.',
    note: 'Renamed in 1.21.5',
  },
  {
    id: 'trim_material_item_model',
    description: 'Trim material "item_model_index" field removed (1.21.5)',
    match: 'item_model_index',
    minVersion: '1.21.5',
    fix: 'Remove item_model_index for 1.21.5+.',
    note: 'Removed in 1.21.5',
  },
  {
    id: 'item_model_definition',
    description: 'Item model definition files (assets/<ns>/items/<id>.json) require 1.21.4+',
    match: 'items/.*\\.json',
    minVersion: '1.21.4',
    fix: 'Item model definition system is 1.21.4+; use model overrides for older versions.',
    note: 'New item rendering pipeline added in 1.21.4',
  },
  {
    id: 'item_model_selector',
    description: 'Model selectors (select/condition/rotate) require 1.21.4+',
    match: '(?:selectors|model_selectors|condition)',
    minVersion: '1.21.4',
    fix: 'Model selector system is 1.21.4+ only.',
    note: 'Item model selectors added in 1.21.4',
  },
  {
    id: 'spawn_egg_individual_textures',
    description: 'Individual spawn egg textures (spawn_egg_<entity>.png) require 1.21.5+',
    match: 'spawn_egg_',
    minVersion: '1.21.5',
    fix: 'Spawn egg coloring system was replaced with individual textures in 1.21.5.',
    note: 'All spawn egg textures split into individual files in 1.21.5',
  },
  {
    id: 'shader_core_format',
    description: 'Core shader format changes in 1.21.6+',
    match: 'shaders/',
    minVersion: '1.21.6',
    fix: 'Shader format was updated in 1.21.6; check compatibility with target version.',
    note: 'Shader system updated in 1.21.6 (Chase the Skies)',
  },
  {
    id: 'dialog_registry_rp',
    description: 'Dialog registry files in resource packs require 1.21.6+',
    match: 'dialog/',
    minVersion: '1.21.6',
    fix: 'Dialog system is 1.21.6+ only.',
    note: 'Dialog system added in 1.21.6',
  },
  {
    id: 'model_render_type',
    description: 'Block model "render_type" field requires 1.17+',
    match: 'render_type',
    minVersion: '1.17',
    fix: 'Omit render_type for pre-1.17 resource packs (cutout, translucent, etc).',
    note: 'render_type field added in 1.17',
  },
  {
    id: 'model_element_rotation',
    description: 'Model elements with rotation require 1.16+ format',
    match: 'model.*rotation',
    minVersion: '1.16',
    fix: 'Omit rotation for pre-1.16 models.',
    note: 'Model element rotation added in 1.16',
  },
  {
    id: 'model_ambientocclusion',
    description: 'Model "ambientocclusion" field available since 1.10',
    match: 'ambientocclusion',
    minVersion: '1.10',
    fix: 'Omit ambientocclusion for pre-1.10 resource packs.',
    note: 'Added in 1.10',
  },
  {
    id: 'model_guilight',
    description: 'Model "gui_light" field available since 1.11',
    match: 'gui_light',
    minVersion: '1.11',
    fix: 'Omit gui_light for pre-1.11 resource packs.',
    note: 'Added in 1.11',
  },
  {
    id: 'sound_replace',
    description: 'Sound "replace" field requires 1.16.2+',
    match: 'sounds.*replace',
    minVersion: '1.16.2',
    fix: 'Remove replace field for pre-1.16.2.',
    note: 'Added in 1.16.2',
  },
  {
    id: 'atlas_source',
    description: 'Atlas "sources" field requires 1.19+',
    match: 'atlases/',
    minVersion: '1.19',
    fix: 'Atlases directory is 1.19+. Use resource-pack-only atlas for older.',
    note: 'Atlas system added in 1.19',
  },
  {
    id: 'atlas_palette',
    description: 'Atlas "palette" source type requires 1.19.4+',
    match: 'palette',
    minVersion: '1.19.4',
    fix: 'Remove palette source for pre-1.19.4.',
    note: 'Palette source added 1.19.4',
  },
  {
    id: 'atlas_paletted_permutations',
    description: 'Atlas "paletted_permutations" source type requires 1.20+',
    match: 'paletted_permutations',
    minVersion: '1.20',
    fix: 'paletted_permutations is 1.20+; use individual texture files for older versions.',
    note: 'Added in 1.20 (Trails & Tales)',
  },
  {
    id: 'particle_texture',
    description: 'Particle "textures" field requires 1.13+',
    match: 'particle.*textures',
    minVersion: '1.13',
    fix: 'Pre-1.13 particles use a different file format.',
    note: 'Particle system overhauled in 1.13',
  },
  {
    id: 'particle_type_json',
    description: 'Particle type JSON definitions require 1.20.5+',
    match: 'particles/.*\\.json',
    minVersion: '1.20.5',
    fix: 'Particle JSON format changed in 1.20.5.',
    note: 'Particle format updated with item component system',
  },
  {
    id: 'blockstate_multipart',
    description: 'Blockstate "multipart" variant requires 1.14+',
    match: 'multipart',
    minVersion: '1.14',
    fix: 'Use variants instead of multipart for pre-1.14.',
    note: 'Multipart blockstates added in 1.14',
  },
  {
    id: 'lang_unicode',
    description: 'Language files with Unicode escapes have been standard since 1.13',
    match: 'lang/',
    minVersion: '1.13',
    fix: 'Language files work across all versions >= 1.13.',
    note: 'JSON lang files introduced in 1.13',
  },
  {
    id: 'entity_model_overrides',
    description: 'Entity model render_type overrides require 1.19.4+',
    match: 'entity.*render_type',
    minVersion: '1.19.4',
    fix: 'Entity render type overrides are 1.19.4+ only.',
    note: 'Display entity render types added in 1.19.4',
  },
  {
    id: 'font_shift_provider',
    description: 'Font "shift" provider (horizontal offset) requires 1.20.5+',
    match: 'font.*shift',
    minVersion: '1.20.5',
    fix: 'Font shift provider is 1.20.5+ only.',
    note: 'Font shift provider added in 1.20.5',
  },
  {
    id: 'model_tint_source',
    description: 'Block model "tint_source" field requires 1.21.4+',
    match: 'tint_source',
    minVersion: '1.21.4',
    fix: 'tint_source is 1.21.4+ only.',
    note: 'Added in 1.21.4',
  },
  {
    id: 'painting_inline_variant',
    description: 'Inline painting variants require pre-1.21.6',
    match: 'painting.*variant',
    minVersion: '1.21',
    maxVersion: '1.21.5',
    fix: 'Inline painting variants removed in 1.21.6; use registry references instead.',
    note: 'Painting variants changed to registry-only in 1.21.6',
  },
  {
    id: 'dimension_type_fields',
    description: 'Dimension type definitions expanded in 1.21.6+',
    match: 'dimension_type',
    minVersion: '1.16',
    fix: 'Dimension type format changed across versions; check compatibility.',
    note: 'Dimension system introduced 1.16, expanded 1.21.6',
  },
  {
    id: 'cow_variant_textures',
    description: 'Cow variant textures (cow_cold.png, cow_warm.png) require 1.21.5+',
    match: 'entity/cow.*(?:cold|warm|temperate)',
    minVersion: '1.21.5',
    fix: 'Cow variant textures are 1.21.5+ only.',
    note: 'Cow variants added in 1.21.5',
  },
  {
    id: 'armor_trim_models',
    description: 'Armor trim model system changed in 1.21.5+',
    match: 'armor_trim',
    minVersion: '1.20',
    fix: 'Armor trim format changed significantly in 1.21.5.',
    note: 'Trim format updated in 1.21.5',
  },
]
