import { VersionData } from "../types";

// Version knowledge for Minecraft Java Edition 1.21.x.
// This is the reference data used by the validator, autocomplete and compiler.

export const V1_21: VersionData = {
  version: "1.21",
  packFormat: 48,
  label: "1.21",
  commands: {
    execute: {
      name: "execute",
      description:
        "Executes another command, potentially as another entity, at a different location, or conditionally.",
      syntax:
        "execute <subcommands...> run <command>",
      arguments: [
        { name: "subcommands", kind: "custom", required: true, description: "Condition/context chain" },
        { name: "command", kind: "command", required: true, description: "The command to run" },
      ],
    },
    function: {
      name: "function",
      description: "Runs a function, or functions in a tag, as the current executor.",
      syntax: "function <function>",
      arguments: [
        { name: "function", kind: "function", required: true, description: "Namespace:path of a function or tag" },
      ],
    },
    particle: {
      name: "particle",
      description: "Spawns a particle effect in the world.",
      syntax: "particle <particle> [<pos>] [<delta>] <speed> <count> [<visibility>]",
      arguments: [
        { name: "particle", kind: "particle", required: true, description: "Particle id", registry: "particles" },
        { name: "pos", kind: "position", required: false, description: "Position" },
        { name: "delta", kind: "coordinates", required: false, description: "Spawn spread" },
        { name: "speed", kind: "float", required: true, description: "Particle speed" },
        { name: "count", kind: "int", required: true, description: "Number of particles" },
        { name: "visibility", kind: "string", required: false, description: "force | normal" },
      ],
    },
    playsound: {
      name: "playsound",
      description: "Plays a sound effect at a location, for a player.",
      syntax: "playsound <sound> <source> <targets> [<pos>] [<volume>] [<pitch>] [<minVolume>]",
      arguments: [
        { name: "sound", kind: "sound", required: true, description: "Sound event", registry: "sounds" },
        { name: "source", kind: "string", required: true, description: "master | music | record | weather | block | hostile | neutral | player | ambient | voice" },
        { name: "targets", kind: "selector", required: true, description: "Players to hear the sound" },
        { name: "pos", kind: "position", required: false, description: "Sound position" },
        { name: "volume", kind: "float", required: false, description: "Volume (default 1.0)" },
        { name: "pitch", kind: "float", required: false, description: "Pitch (0.5-2.0)" },
        { name: "minVolume", kind: "float", required: false, description: "Min volume beyond range" },
      ],
    },
    scoreboard: {
      name: "scoreboard",
      description: "Manage scoreboard objectives and player scores.",
      syntax: "scoreboard objectives ... | scoreboard players ...",
      arguments: [
        { name: "action", kind: "custom", required: true, description: "objectives | players" },
        { name: "subaction", kind: "custom", required: true, description: "Sub-command" },
        { name: "objective", kind: "objective", required: true, description: "Objective name", registry: "objectives" },
        { name: "target", kind: "selector", required: true, description: "Score holder" },
        { name: "value", kind: "int", required: false, description: "Score value" },
      ],
    },
    summon: {
      name: "summon",
      description: "Spawns an entity at a location.",
      syntax: "summon <entity> [<pos>] [<nbt>]",
      arguments: [
        { name: "entity", kind: "entity", required: true, description: "Entity type", registry: "entities" },
        { name: "pos", kind: "position", required: false, description: "Spawn position" },
        { name: "nbt", kind: "nbt", required: false, description: "Entity NBT data" },
      ],
    },
    kill: {
      name: "kill",
      description: "Kills the target entity.",
      syntax: "kill [<targets>]",
      arguments: [
        { name: "targets", kind: "selector", required: false, description: "Entities to kill (default = self)" },
      ],
    },
    tp: {
      name: "tp",
      description: "Teleports an entity to a location or to another entity.",
      syntax: "tp <targets> <location> | tp <targets> <destination>",
      arguments: [
        { name: "targets", kind: "selector", required: true, description: "Entities to teleport" },
        { name: "location", kind: "position", required: false, description: "Destination position" },
        { name: "destination", kind: "selector", required: false, description: "Destination entity" },
      ],
    },
    effect: {
      name: "effect",
      description: "Gives or removes a status effect.",
      syntax: "effect give <targets> <effect> [<seconds>] [<amplifier>] [<hideParticles>] | effect clear <targets> [<effect>]",
      arguments: [
        { name: "subaction", kind: "custom", required: true, description: "give | clear" },
        { name: "targets", kind: "selector", required: true, description: "Targets" },
        { name: "effect", kind: "effect", required: true, description: "Effect id", registry: "effects" },
        { name: "seconds", kind: "int", required: false, description: "Duration in seconds" },
        { name: "amplifier", kind: "int", required: false, description: "Effect level (0-based)" },
        { name: "hideParticles", kind: "bool", required: false, description: "Hide particles" },
      ],
    },
    setblock: {
      name: "setblock",
      description: "Sets a block at a position.",
      syntax: "setblock <pos> <block> [<state>]",
      arguments: [
        { name: "pos", kind: "position", required: true, description: "Position" },
        { name: "block", kind: "block", required: true, description: "Block id", registry: "blocks" },
        { name: "state", kind: "custom", required: false, description: "Block state / destroy / keep / replace" },
      ],
    },
    fill: {
      name: "fill",
      description: "Fills a region between two positions with a block.",
      syntax: "fill <from> <to> <block> [<mode>]",
      arguments: [
        { name: "from", kind: "position", required: true, description: "Start corner" },
        { name: "to", kind: "position", required: true, description: "End corner" },
        { name: "block", kind: "block", required: true, description: "Block id", registry: "blocks" },
        { name: "mode", kind: "custom", required: false, description: "destroy | hollow | outline | replace | keep" },
      ],
    },
    schedule: {
      name: "schedule",
      description: "Schedules a function to run after a delay in ticks.",
      syntax: "schedule function <function> <time> [append|replace]",
      arguments: [
        { name: "subaction", kind: "custom", required: true, description: "function | clear" },
        { name: "function", kind: "function", required: true, description: "Function to schedule" },
        { name: "time", kind: "time", required: true, description: "Delay in ticks" },
      ],
    },
    tellraw: {
      name: "tellraw",
      description: "Sends a JSON text message to targets.",
      syntax: "tellraw <targets> <message>",
      arguments: [
        { name: "targets", kind: "selector", required: true, description: "Targets" },
        { name: "message", kind: "json", required: true, description: "JSON text component" },
      ],
    },
    title: {
      name: "title",
      description: "Sends a title, subtitle, actionbar or titles clear to targets.",
      syntax: "title <targets> <action> <value>",
      arguments: [
        { name: "targets", kind: "selector", required: true, description: "Targets" },
        { name: "action", kind: "custom", required: true, description: "title | subtitle | actionbar | times | clear | reset" },
        { name: "value", kind: "json", required: false, description: "Text / time values" },
      ],
    },
    give: {
      name: "give",
      description: "Gives an item to a player.",
      syntax: "give <targets> <item> [<count>]",
      arguments: [
        { name: "targets", kind: "selector", required: true, description: "Players" },
        { name: "item", kind: "item", required: true, description: "Item id", registry: "items" },
        { name: "count", kind: "int", required: false, description: "Stack count" },
      ],
    },
    clear: {
      name: "clear",
      description: "Clears items from a player's inventory.",
      syntax: "clear [<targets>] [<item>] [<count>]",
      arguments: [
        { name: "targets", kind: "selector", required: false, description: "Players" },
        { name: "item", kind: "item", required: false, description: "Item to clear", registry: "items" },
        { name: "count", kind: "int", required: false, description: "Count to remove" },
      ],
    },
    tag: {
      name: "tag",
      description: "Adds or removes a tag on an entity.",
      syntax: "tag <targets> add <name> | tag <targets> remove <name> | tag <targets> list",
      arguments: [
        { name: "targets", kind: "selector", required: true, description: "Targets" },
        { name: "action", kind: "custom", required: true, description: "add | remove | list" },
        { name: "name", kind: "string", required: false, description: "Tag name" },
      ],
    },
    data: {
      name: "data",
      description: "Gets, merges or removes NBT data on entities, blocks and storage.",
      syntax: "data get/set/merge/remove ...",
      arguments: [
        { name: "action", kind: "custom", required: true, description: "get | merge | modify | remove" },
        { name: "target", kind: "custom", required: true, description: "block | entity | storage" },
        { name: "nbt", kind: "nbt", required: false, description: "NBT path / value" },
      ],
    },
    gamerule: {
      name: "gamerule",
      description: "Sets or queries a game rule.",
      syntax: "gamerule <rule> [<value>]",
      arguments: [
        { name: "rule", kind: "gamerule", required: true, description: "Game rule", registry: "gamerules" },
        { name: "value", kind: "custom", required: false, description: "Rule value" },
      ],
    },
    advancement: {
      name: "advancement",
      description: "Grants or revokes advancements.",
      syntax: "advancement grant/revoke <targets> <everything|from|through|until|only> <advancement>",
      arguments: [
        { name: "action", kind: "custom", required: true, description: "grant | revoke" },
        { name: "targets", kind: "selector", required: true, description: "Targets" },
        { name: "mode", kind: "custom", required: true, description: "everything | from | through | until | only" },
        { name: "advancement", kind: "custom", required: false, description: "Advancement id or criteria" },
      ],
    },
    recipe: {
      name: "recipe",
      description: "Grants or revokes recipes.",
      syntax: "recipe <give|take> <targets> <recipe|*>",
      arguments: [
        { name: "action", kind: "custom", required: true, description: "give | take" },
        { name: "targets", kind: "selector", required: true, description: "Targets" },
        { name: "recipe", kind: "custom", required: true, description: "Recipe id or *" },
      ],
    },
    weather: {
      name: "weather",
      description: "Sets the weather.",
      syntax: "weather <clear|rain|thunder> [<duration>]",
      arguments: [
        { name: "weather", kind: "custom", required: true, description: "clear | rain | thunder" },
        { name: "duration", kind: "int", required: false, description: "Duration in seconds" },
      ],
    },
    time: {
      name: "time",
      description: "Sets or adds to the world time.",
      syntax: "time set <time> | time add <time> | time query <day|daytime|gametime>",
      arguments: [
        { name: "action", kind: "custom", required: true, description: "set | add | query" },
        { name: "value", kind: "time", required: true, description: "Time value" },
      ],
    },
    say: {
      name: "say",
      description: "Broadcasts a message in chat.",
      syntax: "say <message>",
      arguments: [
        { name: "message", kind: "text", required: true, description: "Message text" },
      ],
    },
    msg: {
      name: "msg",
      description: "Sends a private message to a player.",
      syntax: "msg <targets> <message>",
      arguments: [
        { name: "targets", kind: "selector", required: true, description: "Players" },
        { name: "message", kind: "text", required: true, description: "Message text" },
      ],
    },
    trigger: {
      name: "trigger",
      description: "Sets a trigger objective value.",
      syntax: "trigger <objective> [add <value> | set <value>]",
      arguments: [
        { name: "objective", kind: "objective", required: true, description: "Trigger objective", registry: "objectives" },
        { name: "action", kind: "custom", required: false, description: "add | set" },
        { name: "value", kind: "int", required: false, description: "Value" },
      ],
    },
    clearspawnpoint: { name: "clearspawnpoint", description: "Clears the spawn point of a player.", syntax: "clearspawnpoint [<targets>]", arguments: [{ name: "targets", kind: "selector", required: false, description: "Players" }] },
    setworldspawn: { name: "setworldspawn", description: "Sets the world spawn point.", syntax: "setworldspawn [<pos>] [<angle>]", arguments: [{ name: "pos", kind: "position", required: false, description: "Position" }, { name: "angle", kind: "rotation", required: false, description: "Facing" }] },
    forceload: { name: "forceload", description: "Manages force-loaded chunks.", syntax: "forceload ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "add | remove | query" }] },
    locate: { name: "locate", description: "Locates the nearest structure.", syntax: "locate structure <structure>", arguments: [{ name: "subaction", kind: "custom", required: true, description: "structure | biome" }, { name: "target", kind: "custom", required: true, description: "Structure/biome id" }] },
    debug: { name: "debug", description: "Starts/stops the debug profiler.", syntax: "debug <start|stop|function>", arguments: [{ name: "subaction", kind: "custom", required: true, description: "start | stop | function" }] },
    // execute subcommands are handled via the generic execute command; these are for documentation only.
    attribute: { name: "attribute", description: "Gets or modifies an entity attribute.", syntax: "attribute <target> <attribute> ...", arguments: [{ name: "target", kind: "selector", required: true, description: "Target" }, { name: "attribute", kind: "custom", required: true, description: "Attribute id" }] },
    bossbar: { name: "bossbar", description: "Manages boss bars.", syntax: "bossbar ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "add | remove | set | get" }] },
    camera: { name: "camera", description: "Controls player camera.", syntax: "camera <targets> ...", arguments: [{ name: "targets", kind: "selector", required: true, description: "Targets" }, { name: "subaction", kind: "custom", required: true, description: "set | clear" }] },
    clone: { name: "clone", description: "Copies blocks between regions.", syntax: "clone <from> <to> <destination> [<maskMode>] [<cloneMode>]", arguments: [{ name: "from", kind: "position", required: true, description: "Source start" }, { name: "to", kind: "position", required: true, description: "Source end" }, { name: "destination", kind: "position", required: true, description: "Destination" }] },
    damage: { name: "damage", description: "Deals damage to an entity.", syntax: "damage <target> <amount> [<damageType>] [at <pos>] [by <entity>] [from <entity>] [exhaustion <amount>]", arguments: [{ name: "target", kind: "selector", required: true, description: "Target" }, { name: "amount", kind: "float", required: true, description: "Damage amount" }, { name: "damageType", kind: "custom", required: false, description: "Damage type" }] },
    difficulty: { name: "difficulty", description: "Sets the difficulty.", syntax: "difficulty <peaceful|easy|normal|hard>", arguments: [{ name: "difficulty", kind: "custom", required: true, description: "peaceful | easy | normal | hard" }] },
    drop: { name: "drop", description: "Spawns an item or block as a drop.", syntax: "drop ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "give | spawn" }] },
    experience: { name: "experience", description: "Grants or removes experience.", syntax: "experience <add|set|query> <targets> <amount> [points|levels]", arguments: [{ name: "action", kind: "custom", required: true, description: "add | set | query" }, { name: "targets", kind: "selector", required: true, description: "Targets" }, { name: "amount", kind: "int", required: true, description: "Amount" }] },
    input: { name: "input", description: "Reads player input state.", syntax: "input ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "Sub-command" }] },
    item: { name: "item", description: "Modifies items in inventories.", syntax: "item ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "modify | replace" }] },
    jfr: { name: "jfr", description: "Manages Java Flight Recorder.", syntax: "jfr <start|stop>", arguments: [{ name: "subaction", kind: "custom", required: true, description: "start | stop" }] },
    list: { name: "list", description: "Lists online players.", syntax: "list [uuids]", arguments: [{ name: "uuids", kind: "custom", required: false, description: "Optional uuids flag" }] },
    particle_ex: { name: "particle_ex", description: "(Placeholder) particle with per-source modifiers.", syntax: "particle_ex ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "Sub-command" }] },
    playsound_ex: { name: "playsound_ex", description: "(Placeholder) sound with per-source modifiers.", syntax: "playsound_ex ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "Sub-command" }] },
    ride: { name: "ride", description: "Controls riding entities.", syntax: "ride <target> <mount|dismount> [<vehicle>]", arguments: [{ name: "target", kind: "selector", required: true, description: "Target" }, { name: "action", kind: "custom", required: true, description: "mount | dismount" }] },
    return: { name: "return", description: "Returns a value from a function.", syntax: "return <value> | return fail | return run <command>", arguments: [{ name: "value", kind: "custom", required: true, description: "Return value" }] },
    ride_fall: { name: "ride_fall", description: "Deprecated in 1.21, use return fail/run.", syntax: "ride_fall ...", arguments: [] },
    random: { name: "random", description: "Generates random values.", syntax: "random <value|roll|...> ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "value | roll | reset" }] },
    scoreboard_target: { name: "scoreboard_target", description: "(internal) scoreboard target reference.", syntax: "scoreboard_target ...", arguments: [] },
    spectate: { name: "spectate", description: "Makes a spectator spectate an entity.", syntax: "spectate [<target>] [<player>]", arguments: [{ name: "target", kind: "selector", required: false, description: "Entity to spectate" }, { name: "player", kind: "selector", required: false, description: "Player" }] },
    spreadplayers: { name: "spreadplayers", description: "Teleports entities randomly within an area.", syntax: "spreadplayers <center> <spreadDistance> <maxRange> <respectTeams> <targets>", arguments: [{ name: "center", kind: "position", required: true, description: "Center" }, { name: "spreadDistance", kind: "float", required: true, description: "Min spread" }, { name: "maxRange", kind: "float", required: true, description: "Max range" }, { name: "respectTeams", kind: "bool", required: true, description: "Respect teams" }, { name: "targets", kind: "selector", required: true, description: "Targets" }] },
    startsound: { name: "startsound", description: "Starts a sound (music/jukebox).", syntax: "startsound <sound> [<targets>]", arguments: [{ name: "sound", kind: "sound", required: true, description: "Sound event", registry: "sounds" }, { name: "targets", kind: "selector", required: false, description: "Targets" }] },
    stopsound: { name: "stopsound", description: "Stops a sound.", syntax: "stopsound <targets> [<source>] [<sound>]", arguments: [{ name: "targets", kind: "selector", required: true, description: "Targets" }, { name: "source", kind: "custom", required: false, description: "Source" }, { name: "sound", kind: "sound", required: false, description: "Sound", registry: "sounds" }] },
    team: { name: "team", description: "Manages teams.", syntax: "team ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "add | remove | join | leave | modify | empty | list" }] },
    teammsg: { name: "teammsg", description: "Sends a message to the team.", syntax: "teammsg <message>", arguments: [{ name: "message", kind: "text", required: true, description: "Message" }] },
    test: { name: "test", description: "Runs test framework functions.", syntax: "test ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "run | rununtil | runfailed | clear | ..." }] },
    tick: { name: "tick", description: "Controls the tick rate.", syntax: "tick ...", arguments: [{ name: "subaction", kind: "custom", required: true, description: "query | rate | freeze | step | reset" }] },
    transfer: { name: "transfer", description: "Transfers a player to another server.", syntax: "transfer <targets> <host> [<port>]", arguments: [{ name: "targets", kind: "selector", required: true, description: "Targets" }, { name: "host", kind: "string", required: true, description: "Server host" }, { name: "port", kind: "int", required: false, description: "Port" }] },
    wait: { name: "wait", description: "Pauses execution in datapack functions.", syntax: "wait <ticks>", arguments: [{ name: "ticks", kind: "int", required: true, description: "Ticks to wait" }] },
    worlds: { name: "worlds", description: "Lists worlds.", syntax: "worlds list", arguments: [{ name: "subaction", kind: "custom", required: true, description: "list" }] },
  },

  particles: {
    "minecraft:ash": { id: "minecraft:ash", name: "Ash", hasOptions: false },
    "minecraft:block": { id: "minecraft:block", name: "Block", hasOptions: true },
    "minecraft:block_marker": { id: "minecraft:block_marker", name: "Block Marker", hasOptions: true },
    "minecraft:bubble": { id: "minecraft:bubble", name: "Bubble", hasOptions: false },
    "minecraft:bubble_pop": { id: "minecraft:bubble_pop", name: "Bubble Pop", hasOptions: false },
    "minecraft:campfire_cosy_smoke": { id: "minecraft:campfire_cosy_smoke", name: "Campfire Cosy Smoke", hasOptions: false },
    "minecraft:campfire_signal_smoke": { id: "minecraft:campfire_signal_smoke", name: "Campfire Signal Smoke", hasOptions: false },
    "minecraft:cloud": { id: "minecraft:cloud", name: "Cloud", hasOptions: false },
    "minecraft:crit": { id: "minecraft:crit", name: "Critical Hit", hasOptions: false },
    "minecraft:damage_indicator": { id: "minecraft:damage_indicator", name: "Damage Indicator", hasOptions: false },
    "minecraft:dragon_breath": { id: "minecraft:dragon_breath", name: "Dragon Breath", hasOptions: false },
    "minecraft:dripping_dripstone_lava": { id: "minecraft:dripping_dripstone_lava", name: "Dripping Dripstone Lava", hasOptions: false },
    "minecraft:dripping_lava": { id: "minecraft:dripping_lava", name: "Dripping Lava", hasOptions: false },
    "minecraft:dripping_water": { id: "minecraft:dripping_water", name: "Dripping Water", hasOptions: false },
    "minecraft:dust": { id: "minecraft:dust", name: "Dust", hasOptions: true },
    "minecraft:dust_color_transition": { id: "minecraft:dust_color_transition", name: "Dust Color Transition", hasOptions: true },
    "minecraft:effect": { id: "minecraft:effect", name: "Magic Effect", hasOptions: false },
    "minecraft:elder_guardian": { id: "minecraft:elder_guardian", name: "Elder Guardian", hasOptions: false },
    "minecraft:electric_spark": { id: "minecraft:electric_spark", name: "Electric Spark", hasOptions: false },
    "minecraft:enchant": { id: "minecraft:enchant", name: "Enchant", hasOptions: false },
    "minecraft:enchanted_hit": { id: "minecraft:enchanted_hit", name: "Enchanted Hit", hasOptions: false },
    "minecraft:end_rod": { id: "minecraft:end_rod", name: "End Rod", hasOptions: false },
    "minecraft:entity_effect": { id: "minecraft:entity_effect", name: "Entity Effect", hasOptions: false },
    "minecraft:explosion": { id: "minecraft:explosion", name: "Explosion", hasOptions: false },
    "minecraft:explosion_emitter": { id: "minecraft:explosion_emitter", name: "Explosion Emitter", hasOptions: false },
    "minecraft:falling_dust": { id: "minecraft:falling_dust", name: "Falling Dust", hasOptions: true },
    "minecraft:falling_lava": { id: "minecraft:falling_lava", name: "Falling Lava", hasOptions: false },
    "minecraft:falling_water": { id: "minecraft:falling_water", name: "Falling Water", hasOptions: false },
    "minecraft:firework": { id: "minecraft:firework", name: "Firework", hasOptions: true },
    "minecraft:flame": { id: "minecraft:flame", name: "Flame", hasOptions: false },
    "minecraft:flash": { id: "minecraft:flash", name: "Flash", hasOptions: false },
    "minecraft:glow": { id: "minecraft:glow", name: "Glow", hasOptions: false },
    "minecraft:glow_squid_ink": { id: "minecraft:glow_squid_ink", name: "Glow Squid Ink", hasOptions: false },
    "minecraft:happy_villager": { id: "minecraft:happy_villager", name: "Happy Villager", hasOptions: false },
    "minecraft:heart": { id: "minecraft:heart", name: "Heart", hasOptions: false },
    "minecraft:instant_effect": { id: "minecraft:instant_effect", name: "Instant Effect", hasOptions: false },
    "minecraft:item": { id: "minecraft:item", name: "Item", hasOptions: true },
    "minecraft:item_slime": { id: "minecraft:item_slime", name: "Item Slime", hasOptions: true },
    "minecraft:item_snowball": { id: "minecraft:item_snowball", name: "Item Snowball", hasOptions: true },
    "minecraft:item_cobweb": { id: "minecraft:item_cobweb", name: "Item Cobweb", hasOptions: true },
    "minecraft:large_smoke": { id: "minecraft:large_smoke", name: "Large Smoke", hasOptions: false },
    "minecraft:lava": { id: "minecraft:lava", name: "Lava", hasOptions: false },
    "minecraft:mycelium": { id: "minecraft:mycelium", name: "Mycelium", hasOptions: false },
    "minecraft:nautilus": { id: "minecraft:nautilus", name: "Nautilus", hasOptions: false },
    "minecraft:note": { id: "minecraft:note", name: "Note", hasOptions: true },
    "minecraft:poof": { id: "minecraft:poof", name: "Poof", hasOptions: false },
    "minecraft:portal": { id: "minecraft:portal", name: "Portal", hasOptions: false },
    "minecraft:rain": { id: "minecraft:rain", name: "Rain", hasOptions: false },
    "minecraft:scrape": { id: "minecraft:scrape", name: "Scrape", hasOptions: false },
    "minecraft:smoke": { id: "minecraft:smoke", name: "Smoke", hasOptions: false },
    "minecraft:sneeze": { id: "minecraft:sneeze", name: "Sneeze", hasOptions: false },
    "minecraft:soul": { id: "minecraft:soul", name: "Soul", hasOptions: false },
    "minecraft:soul_fire_flame": { id: "minecraft:soul_fire_flame", name: "Soul Fire Flame", hasOptions: false },
    "minecraft:spit": { id: "minecraft:spit", name: "Spit", hasOptions: false },
    "minecraft:splash": { id: "minecraft:splash", name: "Splash", hasOptions: false },
    "minecraft:squid_ink": { id: "minecraft:squid_ink", name: "Squid Ink", hasOptions: false },
    "minecraft:sweep_attack": { id: "minecraft:sweep_attack", name: "Sweep Attack", hasOptions: false },
    "minecraft:totem_of_undying": { id: "minecraft:totem_of_undying", name: "Totem of Undying", hasOptions: false },
    "minecraft:underwater": { id: "minecraft:underwater", name: "Underwater", hasOptions: false },
    "minecraft:vibration": { id: "minecraft:vibration", name: "Vibration", hasOptions: true },
    "minecraft:white_ash": { id: "minecraft:white_ash", name: "White Ash", hasOptions: false },
    "minecraft:witch": { id: "minecraft:witch", name: "Witch", hasOptions: false },
  },

  entities: {
    "minecraft:allay": { id: "minecraft:allay", type: "passive", name: "Allay" },
    "minecraft:armadillo": { id: "minecraft:armadillo", type: "passive", name: "Armadillo" },
    "minecraft:arrow": { id: "minecraft:arrow", type: "projectile", name: "Arrow" },
    "minecraft:axolotl": { id: "minecraft:axolotl", type: "passive", name: "Axolotl" },
    "minecraft:bat": { id: "minecraft:bat", type: "passive", name: "Bat" },
    "minecraft:bee": { id: "minecraft:bee", type: "passive", name: "Bee" },
    "minecraft:blaze": { id: "minecraft:blaze", type: "hostile", name: "Blaze" },
    "minecraft:bogged": { id: "minecraft:bogged", type: "hostile", name: "Bogged" },
    "minecraft:breeze": { id: "minecraft:breeze", type: "hostile", name: "Breeze" },
    "minecraft:breeze_wind_charge": { id: "minecraft:breeze_wind_charge", type: "projectile", name: "Breeze Wind Charge" },
    "minecraft:camel": { id: "minecraft:camel", type: "passive", name: "Camel" },
    "minecraft:cat": { id: "minecraft:cat", type: "passive", name: "Cat" },
    "minecraft:cave_spider": { id: "minecraft:cave_spider", type: "hostile", name: "Cave Spider" },
    "minecraft:chicken": { id: "minecraft:chicken", type: "passive", name: "Chicken" },
    "minecraft:cod": { id: "minecraft:cod", type: "passive", name: "Cod" },
    "minecraft:cow": { id: "minecraft:cow", type: "passive", name: "Cow" },
    "minecraft:creeper": { id: "minecraft:creeper", type: "hostile", name: "Creeper" },
    "minecraft:dolphin": { id: "minecraft:dolphin", type: "passive", name: "Dolphin" },
    "minecraft:donkey": { id: "minecraft:donkey", type: "passive", name: "Donkey" },
    "minecraft:dragon_fireball": { id: "minecraft:dragon_fireball", type: "projectile", name: "Dragon Fireball" },
    "minecraft:drowned": { id: "minecraft:drowned", type: "hostile", name: "Drowned" },
    "minecraft:elder_guardian": { id: "minecraft:elder_guardian", type: "hostile", name: "Elder Guardian" },
    "minecraft:ender_dragon": { id: "minecraft:ender_dragon", type: "hostile", name: "Ender Dragon" },
    "minecraft:enderman": { id: "minecraft:enderman", type: "hostile", name: "Enderman" },
    "minecraft:endermite": { id: "minecraft:endermite", type: "hostile", name: "Endermite" },
    "minecraft:evoker": { id: "minecraft:evoker", type: "hostile", name: "Evoker" },
    "minecraft:experience_bottle": { id: "minecraft:experience_bottle", type: "projectile", name: "Experience Bottle" },
    "minecraft:eye_of_ender": { id: "minecraft:eye_of_ender", type: "projectile", name: "Eye of Ender" },
    "minecraft:fireball": { id: "minecraft:fireball", type: "projectile", name: "Fireball" },
    "minecraft:firework_rocket": { id: "minecraft:firework_rocket", type: "projectile", name: "Firework Rocket" },
    "minecraft:fox": { id: "minecraft:fox", type: "passive", name: "Fox" },
    "minecraft:frog": { id: "minecraft:frog", type: "passive", name: "Frog" },
    "minecraft:ghast": { id: "minecraft:ghast", type: "hostile", name: "Ghast" },
    "minecraft:giant": { id: "minecraft:giant", type: "hostile", name: "Giant" },
    "minecraft:glow_squid": { id: "minecraft:glow_squid", type: "passive", name: "Glow Squid" },
    "minecraft:goat": { id: "minecraft:goat", type: "passive", name: "Goat" },
    "minecraft:guardian": { id: "minecraft:guardian", type: "hostile", name: "Guardian" },
    "minecraft:hoglin": { id: "minecraft:hoglin", type: "hostile", name: "Hoglin" },
    "minecraft:horse": { id: "minecraft:horse", type: "passive", name: "Horse" },
    "minecraft:husk": { id: "minecraft:husk", type: "hostile", name: "Husk" },
    "minecraft:iron_golem": { id: "minecraft:iron_golem", type: "utility", name: "Iron Golem" },
    "minecraft:item": { id: "minecraft:item", type: "other", name: "Item" },
    "minecraft:item_display": { id: "minecraft:item_display", type: "other", name: "Item Display" },
    "minecraft:llama": { id: "minecraft:llama", type: "passive", name: "Llama" },
    "minecraft:magma_cube": { id: "minecraft:magma_cube", type: "hostile", name: "Magma Cube" },
    "minecraft:marker": { id: "minecraft:marker", type: "other", name: "Marker" },
    "minecraft:minecart": { id: "minecraft:minecart", type: "vehicle", name: "Minecart" },
    "minecraft:mooshroom": { id: "minecraft:mooshroom", type: "passive", name: "Mooshroom" },
    "minecraft:mule": { id: "minecraft:mule", type: "passive", name: "Mule" },
    "minecraft:ocelot": { id: "minecraft:ocelot", type: "passive", name: "Ocelot" },
    "minecraft:panda": { id: "minecraft:panda", type: "passive", name: "Panda" },
    "minecraft:parrot": { id: "minecraft:parrot", type: "passive", name: "Parrot" },
    "minecraft:phantom": { id: "minecraft:phantom", type: "hostile", name: "Phantom" },
    "minecraft:pig": { id: "minecraft:pig", type: "passive", name: "Pig" },
    "minecraft:piglin": { id: "minecraft:piglin", type: "hostile", name: "Piglin" },
    "minecraft:piglin_brute": { id: "minecraft:piglin_brute", type: "hostile", name: "Piglin Brute" },
    "minecraft:pillager": { id: "minecraft:pillager", type: "hostile", name: "Pillager" },
    "minecraft:player": { id: "minecraft:player", type: "other", name: "Player" },
    "minecraft:polar_bear": { id: "minecraft:polar_bear", type: "passive", name: "Polar Bear" },
    "minecraft:potion": { id: "minecraft:potion", type: "projectile", name: "Potion" },
    "minecraft:pufferfish": { id: "minecraft:pufferfish", type: "passive", name: "Pufferfish" },
    "minecraft:rabbit": { id: "minecraft:rabbit", type: "passive", name: "Rabbit" },
    "minecraft:ravager": { id: "minecraft:ravager", type: "hostile", name: "Ravager" },
    "minecraft:salmon": { id: "minecraft:salmon", type: "passive", name: "Salmon" },
    "minecraft:sheep": { id: "minecraft:sheep", type: "passive", name: "Sheep" },
    "minecraft:shulker": { id: "minecraft:shulker", type: "hostile", name: "Shulker" },
    "minecraft:silverfish": { id: "minecraft:silverfish", type: "hostile", name: "Silverfish" },
    "minecraft:skeleton": { id: "minecraft:skeleton", type: "hostile", name: "Skeleton" },
    "minecraft:skeleton_horse": { id: "minecraft:skeleton_horse", type: "passive", name: "Skeleton Horse" },
    "minecraft:slime": { id: "minecraft:slime", type: "hostile", name: "Slime" },
    "minecraft:small_fireball": { id: "minecraft:small_fireball", type: "projectile", name: "Small Fireball" },
    "minecraft:snow_golem": { id: "minecraft:snow_golem", type: "utility", name: "Snow Golem" },
    "minecraft:snowball": { id: "minecraft:snowball", type: "projectile", name: "Snowball" },
    "minecraft:spider": { id: "minecraft:spider", type: "hostile", name: "Spider" },
    "minecraft:spore_blossom": { id: "minecraft:spore_blossom", type: "other", name: "Spore Blossom" },
    "minecraft:squid": { id: "minecraft:squid", type: "passive", name: "Squid" },
    "minecraft:stray": { id: "minecraft:stray", type: "hostile", name: "Stray" },
    "minecraft:strider": { id: "minecraft:strider", type: "passive", name: "Strider" },
    "minecraft:tadpole": { id: "minecraft:tadpole", type: "passive", name: "Tadpole" },
    "minecraft:text_display": { id: "minecraft:text_display", type: "other", name: "Text Display" },
    "minecraft:trader_llama": { id: "minecraft:trader_llama", type: "passive", name: "Trader Llama" },
    "minecraft:trident": { id: "minecraft:trident", type: "projectile", name: "Trident" },
    "minecraft:tropical_fish": { id: "minecraft:tropical_fish", type: "passive", name: "Tropical Fish" },
    "minecraft:turtle": { id: "minecraft:turtle", type: "passive", name: "Turtle" },
    "minecraft:vex": { id: "minecraft:vex", type: "hostile", name: "Vex" },
    "minecraft:villager": { id: "minecraft:villager", type: "passive", name: "Villager" },
    "minecraft:vindicator": { id: "minecraft:vindicator", type: "hostile", name: "Vindicator" },
    "minecraft:warden": { id: "minecraft:warden", type: "hostile", name: "Warden" },
    "minecraft:wind_charge": { id: "minecraft:wind_charge", type: "projectile", name: "Wind Charge" },
    "minecraft:witch": { id: "minecraft:witch", type: "hostile", name: "Witch" },
    "minecraft:wither": { id: "minecraft:wither", type: "hostile", name: "Wither" },
    "minecraft:wither_skeleton": { id: "minecraft:wither_skeleton", type: "hostile", name: "Wither Skeleton" },
    "minecraft:wither_skull": { id: "minecraft:wither_skull", type: "projectile", name: "Wither Skull" },
    "minecraft:wolf": { id: "minecraft:wolf", type: "passive", name: "Wolf" },
    "minecraft:zombie": { id: "minecraft:zombie", type: "hostile", name: "Zombie" },
    "minecraft:zombie_horse": { id: "minecraft:zombie_horse", type: "passive", name: "Zombie Horse" },
    "minecraft:zombie_villager": { id: "minecraft:zombie_villager", type: "hostile", name: "Zombie Villager" },
    "minecraft:zombified_piglin": { id: "minecraft:zombified_piglin", type: "hostile", name: "Zombified Piglin" },
  },

  effects: [
    "minecraft:speed", "minecraft:slowness", "minecraft:haste", "minecraft:mining_fatigue",
    "minecraft:strength", "minecraft:instant_health", "minecraft:instant_damage",
    "minecraft:jump_boost", "minecraft:nausea", "minecraft:regeneration", "minecraft:resistance",
    "minecraft:fire_resistance", "minecraft:water_breathing", "minecraft:invisibility",
    "minecraft:blindness", "minecraft:night_vision", "minecraft:hunger", "minecraft:weakness",
    "minecraft:poison", "minecraft:wither", "minecraft:health_boost", "minecraft:absorption",
    "minecraft:saturation", "minecraft:glowing", "minecraft:levitation", "minecraft:luck",
    "minecraft:unluck", "minecraft:slow_falling", "minecraft:conduit_power", "minecraft:dolphins_grace",
    "minecraft:bad_omen", "minecraft:hero_of_the_village", "minecraft:darkness", "minecraft:trial_omen",
    "minecraft:raid_omen", "minecraft:wind_charged", "minecraft:weaving", "minecraft:oozing",
    "minecraft:infested",
  ],

  // Representative item/block sets. Real datasets can be generated via the version-data pipeline;
  // here we cover common blocks & items for autocomplete and validation.
  items: [
    "minecraft:air", "minecraft:stone", "minecraft:granite", "minecraft:diorite", "minecraft:andesite",
    "minecraft:dirt", "minecraft:grass_block", "minecraft:cobblestone", "minecraft:oak_planks",
    "minecraft:bedrock", "minecraft:sand", "minecraft:gravel", "minecraft:iron_ore", "minecraft:coal_ore",
    "minecraft:gold_ore", "minecraft:diamond_ore", "minecraft:oak_log", "minecraft:oak_leaves",
    "minecraft:iron_block", "minecraft:gold_block", "minecraft:diamond_block", "minecraft:emerald_block",
    "minecraft:obsidian", "minecraft:crying_obsidian", "minecraft:netherrack", "minecraft:soul_sand",
    "minecraft:glowstone", "minecraft:redstone_block", "minecraft:water", "minecraft:lava",
    "minecraft:diamond_sword", "minecraft:iron_sword", "minecraft:golden_sword", "minecraft:netherite_sword",
    "minecraft:bow", "minecraft:crossbow", "minecraft:arrow", "minecraft:spectral_arrow",
    "minecraft:diamond_pickaxe", "minecraft:iron_pickaxe", "minecraft:diamond_axe", "minecraft:trident",
    "minecraft:shield", "minecraft:elytra", "minecraft:totem_of_undying", "minecraft:ender_pearl",
    "minecraft:ender_eye", "minecraft:firework_rocket", "minecraft:fire_charge", "minecraft:snowball",
    "minecraft:egg", "minecraft:potion", "minecraft:bread", "minecraft:apple", "minecraft:golden_apple",
    "minecraft:enchanted_golden_apple", "minecraft:cookie", "minecraft:beef", "minecraft:cooked_beef",
    "minecraft:porkchop", "minecraft:chicken", "minecraft:emerald", "minecraft:diamond", "minecraft:iron_ingot",
    "minecraft:gold_ingot", "minecraft:netherite_ingot", "minecraft:redstone", "minecraft:coal",
    "minecraft:stick", "minecraft:oak_boat", "minecraft:minecart", "minecraft:paper", "minecraft:book",
    "minecraft:enchanted_book", "minecraft:experience_bottle", "minecraft:name_tag", "minecraft:lead",
    "minecraft:compass", "minecraft:clock", "minecraft:map", "minecraft:nautilus_shell",
  ],

  blocks: [
    "minecraft:stone", "minecraft:granite", "minecraft:diorite", "minecraft:andesite", "minecraft:dirt",
    "minecraft:grass_block", "minecraft:cobblestone", "minecraft:oak_planks", "minecraft:spruce_planks",
    "minecraft:birch_planks", "minecraft:jungle_planks", "minecraft:acacia_planks", "minecraft:dark_oak_planks",
    "minecraft:bedrock", "minecraft:sand", "minecraft:red_sand", "minecraft:gravel", "minecraft:iron_ore",
    "minecraft:coal_ore", "minecraft:gold_ore", "minecraft:diamond_ore", "minecraft:oak_log", "minecraft:oak_leaves",
    "minecraft:iron_block", "minecraft:gold_block", "minecraft:diamond_block", "minecraft:emerald_block",
    "minecraft:obsidian", "minecraft:crying_obsidian", "minecraft:netherrack", "minecraft:soul_sand",
    "minecraft:glowstone", "minecraft:redstone_block", "minecraft:redstone_lamp", "minecraft:water",
    "minecraft:lava", "minecraft:glass", "minecraft:ice", "minecraft:packed_ice", "minecraft:snow_block",
    "minecraft:torch", "minecraft:lantern", "minecraft:chest", "minecraft:barrel", "minecraft:furnace",
    "minecraft:crafting_table", "minecraft:oak_door", "minecraft:oak_trapdoor", "minecraft:oak_fence",
    "minecraft:oak_slab", "minecraft:oak_stairs", "minecraft:command_block", "minecraft:structure_block",
    "minecraft:jigsaw_block", "minecraft:light",
  ],

  sounds: [
    "minecraft:entity.player.levelup", "minecraft:entity.player.attack.crit",
    "minecraft:entity.player.attack.sweep", "minecraft:entity.ender_dragon.growl",
    "minecraft:entity.wither.spawn", "minecraft:entity.generic.explode",
    "minecraft:entity.generic.extinguish_fire", "minecraft:entity.ghast.scream",
    "minecraft:block.note_block.harp", "minecraft:block.note_block.bell",
    "minecraft:block.note_block.pling", "minecraft:ui.button.click",
    "minecraft:item.trident.return", "minecraft:block.anvil.place",
    "minecraft:block.beacon.activate", "minecraft:entity.player.hurt",
    "minecraft:entity.ender_pearl.throw", "minecraft:ambient.cave",
  ],

  gamerules: [
    "announceAdvancements", "blockExplosionDropDecay", "commandBlockOutput", "commandModificationBlockLimit",
    "disableElytraMovementCheck", "disableRaids", "doDaylightCycle", "doEntityDrops", "doFireTick",
    "doImmediateRespawn", "doInsomnia", "doLimitedCrafting", "doMobLoot", "doMobSpawning",
    "doPatrolSpawning", "doTileDrops", "doTraderSpawning", "doVinesSpread", "doWeatherCycle",
    "drowningDamage", "fallDamage", "fireDamage", "forgiveDeadPlayers", "freezeDamage",
    "globalSoundEvents", "keepInventory", "logAdminCommands", "maxCommandChainLength",
    "maxEntityCramming", "mobExplosionDropDecay", "mobGriefing", "naturalRegeneration",
    "playersSleepingPercentage", "projectilesCanBreakBlocks", "randomTickSpeed", "reducedDebugInfo",
    "sendCommandFeedback", "showBorderEffect", "showCoordinates", "showDeathMessages",
    "spawnRadius", "spectatorsGenerateChunks", "universalAnger", "doWardenSpawning",
    "commandModificationBlockLimit",
  ],

  changes: [
    {
      version: "1.21",
      title: "New commands: transfer, tick, wait, worlds",
      description:
        "1.21 added several new commands and command forms. This version uses pack_format 48.",
    },
  ],
};
